# fly.toml app configuration file generated for search-api-v3 on 2024-11-05T22:28:25+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'search-api-v3'
primary_region = 'iad'
swap_size_mb = 2048

[build]

[[mounts]]
  source = 'cache'
  destination = '/cache'
  initial_size = '20'
  processes = ['app']

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '16gb'
  cpu_kind = 'shared'
  cpus = 8
