# fly.toml app configuration file generated for search-api-v2 on 2024-10-31T12:58:21+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'search-api-v2'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'cache'
  destination = '/cache'
  initial_size = '20'
  processes = ['app']

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '8gb'
  cpu_kind = 'shared'
  cpus = 8
